name: talibantv

# 定时触发 + push 分支触发
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00（北京时间 08:00）
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests eventlet

      # 4️⃣ 运行你的 IPTV 脚本
      - name: Run talibaniptv
        run: python talibaniptv.py

      # 5️⃣ 检查文件生成情况
      - name: Verify zby.txt
        run: |
          if [ ! -f zby.txt ]; then
            echo "::error::zby.txt 文件未生成！"
            exit 1
          fi
          echo "✅ 文件已生成，大小：$(du -h zby.txt | cut -f1)"

      # 6️⃣ 提交并推送文件
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "362213335lkh@gmail.com"
          git config --global user.name "qingtingjjjjjjj"

          git add zby.txt --force
          git commit -m "自动更新 IPTV 列表 $(date +'%Y-%m-%d %H:%M') [skip ci]" --allow-empty
          git push origin main
